application: kaslabselvee
version: 0-2-1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /page/.*
  script: main.py

- url: /admin.*
  script: admin.py
  login: required

- url: /CSS
  static_dir: CSS

- url: /Img
  static_dir: Img

- url: /p/(\d+)
  script: event.py

- url: /kad/(\d+|\d+-\d+)
  script: filter.py

- url: /JS
  static_dir: JS
