application: kaslabselvee
version: 0-2-9-1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /admin.*
  script: admin.py
  login: required

- url: /CSS
  static_dir: CSS

- url: /Img
  static_dir: Img

- url: /p/(\d+)
  script: event.py

- url: /kad
  script: main.py 

- url: /d/(\d+-*|\d+-\d+)
  script: main.py

- url: /kad/(rit|parit|aizparit|sonedel|nakamnedel|somenes)
  script: main.py

- url: /JS
  static_dir: JS
